// smtc_OperKind.h
//

#ifndef LZZ_smtc_OperKind_h
#define LZZ_smtc_OperKind_h
#define LZZ_INLINE inline
namespace smtc
{
  enum OperKind
  {
    CALL_OPER,
    SUBSCR_OPER,
    NEW_ARRAY_OPER,
    DELETE_ARRAY_OPER,
    AND_OPER,
    ASSIGN_OPER,
    BITAND_OPER,
    BITAND_ASSIGN_OPER,
    BITNOT_OPER,
    BITOR_OPER,
    BITOR_ASSIGN_OPER,
    COMMA_OPER,
    DEC_OPER,
    DELETE_OPER,
    DIVIDE_OPER,
    DIVIDE_ASSIGN_OPER,
    EQ_OPER,
    GT_OPER,
    GTEQ_OPER,
    INC_OPER,
    LSHIFT_OPER,
    LSHIFT_ASSIGN_OPER,
    LT_OPER,
    LTEQ_OPER,
    MINUS_OPER,
    MINUS_ASSIGN_OPER,
    MOD_OPER,
    MOD_ASSIGN_OPER,
    NEW_OPER,
    NOT_OPER,
    NOTEQ_OPER,
    OR_OPER,
    PLUS_OPER,
    PLUS_ASSIGN_OPER,
    PTR_OPER,
    PTR_TIMES_OPER,
    RSHIFT_OPER,
    RSHIFT_ASSIGN_OPER,
    TIMES_OPER,
    TIMES_ASSIGN_OPER,
    XOR_OPER,
    XOR_ASSIGN_OPER
  };
}
#undef LZZ_INLINE
#endif
